# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UI test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'DotsLoading'
pod 'Alamofire'
pod 'Kingfisher'
pod 'RealmSwift'
pod 'INSPhotoGallery'
pod 'SwiftyJSON'
pod 'PromiseKit'
pod 'PinLayout'
  # Pods for UI test

end
